modules/control/controllers/ErrorController.php
<?php

namespace app\modules\control\controllers;

use Yii;
use app\common\models\Error;
use app\common\models\ErrorSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ErrorController implements the CRUD actions for Error model.
 */
class ErrorController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
        ];
    }

    /**
     * Lists all Error models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ErrorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Error model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
    	$model = $this->findModel($id);
		$model->makeRead();
		
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Error model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Error();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Error model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Error model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
	
	/**
	 * Позначає помилку прочитаною
	 * Допоміжний медот, котрий дозволяє мітити зрозумілі помилки пакунками без перезавантаження сторінки
	 *
	 * @param array $ids Перелік ідентифікаторів помилок
	 */
	public function actionMakeRead(array $ids=[])
	{
		foreach ($ids as $id) {
			$this->findModel($id)->makeRead();
		}
	}

    /**
     * Finds the Error model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Error the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Error::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/control/controllers/OrderController.php
<?php

namespace app\modules\control\controllers;

use app\common\models\Error;
use app\common\models\ErrorSearch;
use app\modules\apilead\common\adv\models\forms\ApileadStatusDataModel;
use app\modules\apilead\common\traits\ErrorTrait;
use Yii;
use app\common\models\OrderApilead;
use app\common\models\OrderApileadSearch;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for OrderApilead model.
 */
class OrderController extends Controller
{
	use ErrorTrait;
	
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrderApilead models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderApileadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

	public function actionProblem()
	{
		$searchModel = new OrderApileadSearch();
		$dataProvider = $searchModel->searchProblem(Yii::$app->request->queryParams);


		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	public function actionOutdate()
	{
		$searchModel = new OrderApileadSearch();
		$dataProvider = $searchModel->searchOutdate(Yii::$app->request->queryParams);


		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}
	
	

	public function actionError()
	{
		$params 		= Yii::$app->request->queryParams;
		$searchModel	= new OrderApileadSearch();

		$query 			= OrderApilead::getErrorOrdersQueryOld();

		$dataProvider = new ActiveDataProvider([
			'query' => $query,
			'pagination' => [
				'pageSize' => Yii::$app->request->get('dynamicPageSize', 40),
			],
			'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
		]);
		
		$searchModel->load($params);
		
		if (!$searchModel->validate())
			return $dataProvider;

		$query->andFilterWhere([
			'offer_id' => $searchModel->offer_id,
			'system_user_id' => $searchModel->system_user_id,
		]);

//		$query->andFilterWhere(['between', 'created_at', $searchModel->createdTimeStart, $searchModel->createdTimeEnd]);
		$query->andFilterWhere(['between', 'updated_at', $searchModel->updatedTimeStart, $searchModel->updatedTimeEnd]);

		$query->andFilterWhere(['like', 'id', $searchModel->id])
			->andFilterWhere(['like', 'partner_status', $searchModel->partner_status])
			->andFilterWhere(['like', 'system_status', $searchModel->system_status])
			->andFilterWhere(['like', 'partner_order_id', $searchModel->partner_order_id])
			->andFilterWhere(['like', 'system_order_id', $searchModel->system_order_id])
			->andFilterWhere(['like', 'integration_name', $searchModel->integration_name]);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

    /**
     * Displays a single OrderApilead model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
    	$logModel = $this->findModel($id);
    	
		$params 		= Yii::$app->request->queryParams;
		$errorSearchModel	= new ErrorSearch();
//		$query 			= Log::find()->where(['var' => $id]);
		$query 			= $logModel->getError();
	
		$errorDataProvider = new ActiveDataProvider([
			'query' => $query,
			'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
		]);
	
		$errorSearchModel->load($params);
	
		if (!$errorSearchModel->validate())
			return $errorDataProvider;
	
		$query->andFilterWhere([
			'created_at' => $errorSearchModel->created_at,
			'updated_at' => $errorSearchModel->updated_at,
		]);
	
		$query->andFilterWhere(['like', 'category', $errorSearchModel->category])
			->andFilterWhere(['like', 'text', $errorSearchModel->text]);
		
        return $this->render('view', [
            'model' => $logModel,
			'errorSearchModel' => $errorSearchModel,
			'errorDataProvider' => $errorDataProvider,
        ]);
    }

    /**
     * Creates a new OrderApilead model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new OrderApilead();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing OrderApilead model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing OrderApilead model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
	
	/**
	 * Перегляд стану поточного замовлення на стороні партнера
	 *
	 * @return mixed
	 */
	public function actionViewStatus()
	{
		$ids = Yii::$app->request->get('ids', []);
		
		$result = [];
		
		foreach ($ids as $id) {
			try {
				$orderModel = $this->findModel($id);
				
				if (isset($orderModel->config->user->postbackApiKey)) {
					$result[$id] = (new ApileadStatusDataModel(true, [
						'comment' => 'ERROR. Status works via postback',
					]))->getProperties();
					continue;
				}
				
				/**@var \app\modules\apilead\common\adv\handlers\base\BaseStatusHandler $handler*/
				$handler = $orderModel->getStatusHandler();
				
				$responseModel	= $handler->makeStatusRequest();
				$data = $handler->getSystemStatusData($responseModel);
				
				$result[$id] = $data->getProperties();
			} catch (\Exception $e) {
				$result[$id] = ['error' => $e->getMessage()];
			}
		}
		
		return $this->renderJson($result);
	}
	
	/**
	 * Перегляд, чи викуплено замовлення на стороні партнера
	 *
	 * @return mixed
	 */
	public function actionViewRansom()
	{
		$ids = Yii::$app->request->get('ids', []);
		
		$result = [];
		
		foreach ($ids as $id) {
			try {
				$orderModel = $this->findModel($id);
				
				if (isset($orderModel->config->user->postbackApiKey)) {
					$result[$id] = (new ApileadStatusDataModel(true, [
						'comment' => 'ERROR. Status works via postback',
					]))->getProperties();
					continue;
				}
				
				/**@var \app\modules\apilead\common\adv\handlers\base\BaseStatusHandler $handler*/
				$handler = $orderModel->getStatusHandler();
				
				$responseModel	= $handler->makeRansomStatusRequest();
				$data			= $handler->getRansomStatusData($responseModel);
				
				$result[$id] = $data->getProperties();
			} catch (\Exception $e) {
				$result[$id] = ['error' => $e->getMessage()];
			}
		}
		
		return $this->renderJson($result);
	}
	
	/**
	 * Відправити статус поточного замовлення в основну систему
	 *
	 * @return mixed
	 */
	public function actionUpdateStatus()
	{
		$ids = Yii::$app->request->get('ids', []);
		
		$result = [];
		
		foreach ($ids as $id) {
			try {
				$orderModel = $this->findModel($id);
				
				if (isset($orderModel->config->user->postbackApiKey)) {
					$result[$id] = (new ApileadStatusDataModel(true, [
						'comment' => 'ERROR. Status works via postback',
					]))->getProperties();
					continue;
				}
				
				/**@var \app\modules\apilead\common\adv\handlers\base\BaseStatusHandler $handler*/
				$handler = $orderModel->getStatusHandler();
				
				$sentData = $handler->updateStatusInSystem(true);
				
				$result[$id] = $sentData->getProperties();
			} catch (\Exception $e) {
				$result[$id] = ['error' => $e->getMessage()];
			}
		}
		
		return $this->renderJson($result);
	}
	
	/**
	 * Відправити статус поточного замовлення в основну систему
	 *
	 * @return mixed
	 */
	public function actionUpdateStatusByDate()
	{
		$from = Yii::$app->request->get('from');
		$to = Yii::$app->request->get('to');
		
		$fromTimestamp = strtotime($from . ' 00:00:00');
		$toTimestamp = strtotime($to . ' 23:59:59');
		
		$orders = OrderApilead::find()
			->innerJoin(Error::tableName(), 'error.order_id = order.id')
			->where(['error.status' => Error::STATUS_UNREAD])
			->andWhere(['>=', 'error.created_at', $fromTimestamp])
			->andWhere(['<=', 'error.created_at', $toTimestamp])
			->all();
		
		$result = [];
		
		foreach ($orders as $order) {
			try {
				$id = $order->id;
				
				$orderModel = $this->findModel($id);
				
				if (isset($orderModel->config->user->postbackApiKey)) {
					continue;
				}
				
				/**@var \app\modules\apilead\common\adv\handlers\base\BaseStatusHandler $handler*/
				$handler = $orderModel->getStatusHandler();
				
				$sentData = $handler->updateStatusInSystem(true);
			} catch (\Exception $e) {}
		}
		
		$result['status'] = 'OK';
		
		return $this->renderJson($result);
	}
	
	/**
	 * @return mixed
	 */
	public function actionUpdateStatusByAdv()
	{
		$from = Yii::$app->request->get('from');
		$to = Yii::$app->request->get('to');

modules/control/views/order/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\common\models\OrderApilead */

$this->title = 'Create Order Apilead';
$this->params['breadcrumbs'][] = ['label' => 'Order Apileads', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-apilead-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/control/views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\common\models\OrderApilead */

$this->title = 'Update Order Apilead: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Order Apileads', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="order-apilead-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/control/views/order/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\grid\GridView;
use kartik\daterange\DateRangePicker;
use edgardmessias\assets\nprogress\NProgressAsset;

NProgressAsset::register($this);

/* @var $this yii\web\View */
/* @var $model app\common\models\OrderApilead */

$this->registerCss("#nprogress .bar {
  background: yellow;
}");

$jsUpdateStatus = <<<JS
    function getStatusLog(id, date) {
        
        $.ajax({
            url: "/control/order/view-status-log?id="+id+"&date="+date,
            type: 'get',
            success: function(result){
                $("#statusLogContainerId").html(result);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                $("#statusLogContainerId").html("Не вдалий запит!");
            }
        });
    }
JS;

$this->registerJs($jsUpdateStatus, \yii\web\View::POS_END);

$this->title = "Замовлення {$model->system_order_id}";
$this->params['breadcrumbs'][] = ['label' => 'Order Apileads', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->system_order_id;
?>

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_order_view" data-toggle="tab" aria-expanded="true">Замовлення</a></li>
        <li class=""><a href="#tab_order_error" data-toggle="tab" aria-expanded="false">Помилки</a></li>
        <li class=""><a href="#tab_request_log" data-toggle="tab" aria-expanded="false">Запит</a></li>
        <li class=""><a href="#tab_order_log" data-toggle="tab" aria-expanded="false">Журнал</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab_order_view">
        
            <!--<h1><?//= Html::encode($this->title) ?></h1>
            <p>
                <?//= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?//= Html::a('Delete', ['delete', 'id' => $model->id], [
    //                'class' => 'btn btn-danger',
    //                'data' => [
    //                    'confirm' => 'Are you sure you want to delete this item?',
    //                    'method' => 'post',
    //                ],
    //            ]) ?>
            </p>-->
            
            <?if ($model->isStatusUnknown()):?>
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Невідомий статус!</h4>
                    Рекламодавець віддав нам невідомий статус. Потрібно уточнити у рекламодавця, що означає статус {<i><?=$model->partner_status?></i>}. <br>
                    Після чого внести його в файл конфігурації, що відповідає за інтеграцію <b><?=$model->integration_name?></b>
                </div>
            <?endif;?>
            <?if ($model->isProcessingFail()):?>
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Виникла помилка при опитуванні статусу!</h4>
                    Під час опитування статусу, виникла невідома помилка, що спричинила неможливість подальшого опитування. <br>
                    Помилка сталася більше години тому.
                </div>
            <?endif;?>
        
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'offer_id',
                    'system_user_id',
                    'system_order_id',
                    'partner_order_id',
                    'partner_status',
                    'system_status',
                    [
                        'attribute' => 'created_at',
                        'value' => function ($model) {
                            $relative = Yii::$app->formatter->asRelativeTime($model->created_at);
                            $datetime = Yii::$app->formatter->asDatetime($model->created_at);
                            return "{$datetime} ({$relative})";
                        }
                    ],
                    [
                        'attribute' => 'updated_at',
                        'value' => function ($model) {
                            $relative = Yii::$app->formatter->asRelativeTime($model->updated_at);
                            $datetime = Yii::$app->formatter->asDatetime($model->updated_at);
                            return "{$datetime} ({$relative})";
                        }
                    ],
                    [
                        'attribute' => 'request_at',
                        'value' => function ($model) {
                            if (!$model->request_at)
                                return 'Запитів не було.';
                            
                            $relative = Yii::$app->formatter->asRelativeTime($model->request_at);
                            $datetime = Yii::$app->formatter->asDatetime($model->request_at);
                            return "{$datetime} ({$relative})";
                        }
                    ],
                    'processing',
                    'comment:ntext',
                    'integration_name',
                    'integration_module',
    //                'request_data:ntext',
    //                [
    //                    'attribute' => 'request_data',
    //                    'format' => 'raw',
    //                    'value' => function($model) {
    //                        return "<span style='white-space: pre'>" . $model->request_data . "</span>";
    //                    }
    //                ],
    //                'request_url:ntext',
    //                'request_timeout',
    //                'response_code',
    //                'response_result:ntext',
    //                'response_error:ntext',
    //                'incoming_data:ntext',
    //                [
    //                    'attribute' => 'incoming_data',
    //                    'format' => 'raw',
    //                    'value' => function($model) {
    //                        return "<span style='white-space: pre'>" . $model->incoming_data . "</span>";
    //                    }
    //                ],
    //                'incoming_field_id',
    //                'incoming_field_campaign_id',
    //                'incoming_field_name:ntext',
    //                'incoming_field_country',
    //                'incoming_field_phone',
    //                'incoming_field_tz',
    //                'incoming_field_address:ntext',
    //                'incoming_field_user_comment:ntext',
    //                'incoming_field_cost',
    //                'incoming_field_cost_delivery',
    //                'incoming_field_landing_cost',
    //                'incoming_field_user_id',
    //                'incoming_field_web_id',
    //                'incoming_field_stream_id',
    //                'incoming_field_product_id',
    //                'incoming_field_offer_id',
    //                'incoming_field_ip',
    //                'incoming_field_user_agent:ntext',
    //                'incoming_field_landing_currency',
    //                'incoming_field_check_sum',
                ],
            ]) ?>
        </div>
        <div class="tab-pane" id="tab_order_error">
			<?Pjax::begin()?>
			<?= GridView::widget([
				'dataProvider' => $errorDataProvider,
				'rowOptions' => function ($model) {
					if (!$model->isRead())
						return ['class' => 'bg-yellow'];
				},
				'filterModel' => $errorSearchModel,
				'columns' => [
					['class' => 'yii\grid\SerialColumn'],
			
					'category',
					[
						'attribute' => 'text',
						'format' => 'ntext',
						'contentOptions' => ['style' => 'word-break:break-all'],
						'value' => function($model) {
							return substr($model->text, 0, 400);
						}
					],
					'created_at:datetime',
//            'id',
//            'level',
//            'updated_at:datetime',
//            'ip',
//            'var:ntext',
//            'referrer_url:ntext',
//            'request_url:ntext',
//            'status',
			
					[
                        'class' => 'yii\grid\ActionColumn',
						'template' => '{view}',
						'buttons' => [
							'view' => function ($model, $key, $index) {
								$icon = Html::tag('span', '', ['class' => "glyphicon glyphicon-eye-open"]);
								$title = 'Переглянути';
								return Html::a($icon, ['error/view', 'id'=>$index], [
									'title' => $title,
									'aria-label' => $title,
                                    'data-pjax' => '0',
								]);
                            }
                        ],
                    ],
				],
			]); ?>
			<?Pjax::end()?>
        </div>
        <div class="tab-pane" id="tab_request_log">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <p>Надіслано:</p>
                        <p><?=Html::encode($model->request_url)?></p>
                        <p><pre><?=Html::encode($model->request_data)?></pre></p>
                    </div>
                    <div class="col-sm-6">
                        <p>Отримано:</p>
                        <br>
                        <p><pre><?=Html::encode($model->response_result)?></pre></p>
                        <p>HTTP code = <?=Html::encode($model->response_code)?></p>
                        <p>request time = <?=round(Html::encode($model->request_timeout), 2)?> сек.</p>
						<?if ($model->response_error):?>
                            <p><?=Html::encode($model->response_error)?></p>
						<?endif;?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <a href="#spoiler" data-toggle="collapse" class="btn btn-primary">Дані від Apilead</a>

                        <div class="collapse" id="spoiler">
                            <div>
                                <p><pre><?=Html::encode($model->incoming_data)?></pre></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="tab_order_log">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_order_log_bridge" data-toggle="tab" aria-expanded="true">Міст</a></li>
                    <li class=""><a href="#tab_order_log_status" data-toggle="tab" aria-expanded="false">Статус</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab_order_log_bridge">
                        <pre>
<?= Html::encode(@file_get_contents($model->config->getFullLogPath($model->created_at) . 'bridge.log'))?>
                        </pre>
                    </div>
                    <div class="tab-pane" id="tab_order_log_status">
                        <div class="row">
                            <div class="col-sm-3 col-sm-offset-0">
                                <div class="input-group drp-container">
                                    <?=DateRangePicker::widget([
                                        'name'=>'date_log_status',
										'convertFormat'=>true,
                                        'value'=> Yii::$app->formatter->asDate('now'),
                                        'useWithAddon'=>true,
                                        'pluginOptions'=>[
											'locale'=>['format' => 'd.m.Y'],
                                            'singleDatePicker'=>true,
                                            'showDropdowns'=>true
                                        ],
										'pluginEvents' => [
//                                            'change' => "ajaxGetStatusLog(" . Yii::$app->formatter->asDate('now') . ")",
//                                            'change' => "console.log($(\"input[name=date_log_status]\").val())",
//                                            'change' => "console.log({$model->id})",
                                            'apply.daterangepicker' => "function() { getStatusLog({$model->id}, $(\"input[name = date_log_status]\").val()) }",
                                        ],
                                    ]);?>
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-calendar"></i>
                                    </span>
                                </div>
                            </div>

                            <div class="col-sm-5">
                                <span>Починаючи з <?=Yii::$app->formatter->asDate($model->created_at)?> та закінчуючи <?=Yii::$app->formatter->asDatetime($model->updated_at)?></span>
                            </div>
                        </div>
                        
                        <br>
                        
                        <pre id="statusLogContainerId"></pre>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>